# -*- coding: utf-8 -*-
"""
FIGURE 13 — FULL ORGANIZED LATEST WORKFLOW
FIGURE
Local Forcing and AAO Attribution
Southern Ocean / 13 Antarctic Shelf Seas

SOURCE

Extracted and organized from:
    so_sealevel_paper_fig.py

LATEST VERSION SELECTION
The source contains three important Figure 13 revisions:

1. An initial LOW-RAM, checkpointed workflow.
2. A later LOW-RAM, checkpointed workflow explicitly labelled:
       WSC MASK FIX
3. A later FINAL PLOT-ONLY layout correction explicitly labelled:
       CENTERED PANEL H + PARAGRAPH FOOTNOTE
   with the final V3 2-column x 4-row layout.

This standalone script intentionally uses:

    WSC MASK FIX scientific/data-processing workflow
        ->
    latest FINAL V3 plot-only renderer

The earlier initial LOW-RAM workflow and the superseded plot embedded in the
WSC-mask-fixed workflow are excluded.

LOW-RAM / CHECKPOINT STRATEGY PRESERVED
The WSC-mask-fixed processing workflow is designed for Google Colab memory
constraints and preserves these source methods:

1. Process one NetCDF variable at a time.
2. Load one monthly 2-D field at a time.
3. Immediately reduce each field to 13 area-weighted sector means.
4. Close each NetCDF before opening the next large variable.
5. Derive Qnet* month-by-month from SSRD, STRD, SLHF and SSHF.
6. Derive wind-stress curl month-by-month from U10 and V10.
7. Save small sector time series as checkpoint CSV files.
8. Calculate the AAO composite on an automatically coarsened SLA grid.
9. Use online bootstrap sign counts rather than storing all bootstrap maps.
10. Reuse cached sector/composite products when requested.

SCIENTIFIC NOTE ON HEAT FLUX
The source explicitly states that the available radiation variables are
downward SSRD and downward STRD rather than net SSR and net STR.

Therefore the workflow retains the source-defined proxy:

    Qnet* = SSRD + STRD + signed(SLHF) + signed(SSHF)

Qnet* remains labelled as a SURFACE HEAT-FLUX PROXY. The source notes that a
complete physical net surface heat flux would require ERA5 SSR and STR.

FIGURE STRUCTURE — LATEST V3
2 columns x 4 rows:

    Row 1: (a) and (b)
    Row 2: (c) and (d)
    Row 3: (e) and (f)
    Row 4: (g) and (h)

The final plotting block does not recompute the science. It reads the processed
CSV/NetCDF outputs generated by the science stage.

ORGANIZED EXECUTION ORDER
1. Mount Google Drive.
2. Install all required Python packages.
3. Import all required libraries.
4. Define source/output/cache paths.
5. Define low-RAM, composite, bootstrap and AAO settings.
6. Define the 13 Antarctic shelf-sea sectors.
7. Define file/coordinate standardization helpers.
8. Prepare the GEBCO ocean mask.
9. Define area-weighted sector averaging helpers.
10. Process standard monthly variables to 13-sector series.
11. Calculate Qnet* sector series month-by-month.
12. Calculate wind-stress curl sector series month-by-month using the
    WSC-mask-fixed implementation.
13. Read and standardize the AAO/SAM index.
14. Deseasonalize variables and calculate statistical diagnostics.
15. Build/reuse the low-RAM AAO-SLA composite and online bootstrap test.
16. Run the main low-RAM processing/checkpoint workflow.
17. Save the combined sector-driver time-series CSV.
18. Calculate and save panel (a) SLA/steric correlations.
19. Calculate and save panel (b) thermosteric-driver correlations.
20. Calculate and save panel (c) halosteric-driver correlations.
21. Calculate and save panel (d) thermosteric regression coefficients.
22. Calculate and save panel (e) halosteric regression coefficients.
23. Calculate and save panel (g) AAO-SLA lag correlations.
24. Calculate/save panel (h) AAO-SLA composite NetCDF.
25. Read all processed products with the latest final V3 renderer.
26. Rebuild the final 2-column x 4-row figure.
27. Render larger heatmap values, fonts and legends.
28. Restore panel (h) SLA-composite colorbar label.
29. Center panel (h) and apply the final non-overlapping spacing.
30. Render the methodological footnote as one wrapped paragraph.
31. Save final vector PDF.
32. Save final 1080-dpi PNG.
33. Save the final V3 processing/layout log.

MAIN SCIENCE INPUTS
The WSC-mask-fixed workflow uses the source-defined files under:

    /content/drive/MyDrive/SAM_Thesis/Data/
    /content/drive/MyDrive/SAM_Thesis/Processed/EN4_NetCDF_inventory/

including:

    SLA_Antarctic_monthly_2008_2025.nc
    EN4_total_steric_0_1000m_monthly_2008_2025_SO.nc
    EN4_thermosteric_0_1000m_monthly_2008_2025_SO.nc
    EN4_halosteric_0_1000m_monthly_2008_2025_SO.nc
    EN4_OHC_0_1000m_monthly_2008_2025_SO.nc
    OSTIA_SST_monthly_2008_2025_SO.nc
    SW_LW_era.nc
    heatflux_latent_sensible_era.nc
    Wind_U_V_era.nc
    MLD_monthly_2008_2025_SO.nc
    OSTIA_sea_ice_fraction_monthly_2008_2025_SO.nc
    EN4_freshwater_content_0_200m_monthly_2008_2025_SO.nc
    EN4_surface_salinity_anomaly_0_30m_monthly_2008_2025_SO.nc
    P_Snow_era.nc
    EN4_stratification_20_200m_monthly_2008_2025_SO.nc
    GEBCO_2024_CF.nc
    NOAA_CPC_SAM_AAO_monthly_2008_2025.nc

PROCESSED FIGURE 13 OUTPUTS
/content/drive/MyDrive/SAM_Thesis/paper2/

    Fig13_sector_driver_timeseries_LOW_RAM.csv

    Fig13a_SLA_steric_correlations.csv
    Fig13b_thermosteric_driver_correlations.csv
    Fig13c_halosteric_driver_correlations.csv
    Fig13d_thermosteric_regression_coefficients.csv
    Fig13e_halosteric_regression_coefficients.csv
    Fig13g_AAO_SLA_lag_correlations.csv

    Fig13h_AAO_SLA_composite_LOW_RAM.nc

The workflow also retains the source-defined checkpoint directory:

    Fig13_lowRAM_cache/

LATEST FINAL FIGURE OUTPUTS
/content/drive/MyDrive/SAM_Thesis/paper2/

    Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH_1080dpi.png
    Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH.pdf
    Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH_log.txt

LATEST PLOT CORRECTIONS PRESERVED
The source-defined final V3 renderer retains:

    - 2-column x 4-row layout;
    - larger panel titles, labels, legends and tick labels;
    - larger numeric text inside heatmap cells;
    - restored panel (h) colorbar label;
    - panel (h) centered in its final layout;
    - taller title bands to prevent title/variable-label overlap;
    - full labels for SSS anomaly, Snowfall and Stratification;
    - panel (h) colorbar moved next to the map;
    - wrapped paragraph-style methodological footnote;
    - no scientific recomputation in the plotting stage.

ORGANIZATION CHANGES
Only workflow organization and version selection were changed:

    - Google Drive mount is placed first.
    - Package installation is consolidated.
    - Imports are consolidated.
    - The earlier initial low-RAM Figure 13 version is excluded.
    - The WSC MASK FIX version is used for all scientific processing.
    - Its superseded embedded plot is removed.
    - The later FINAL V3 plot-only renderer is used for the final figure.
    - Supplementary Figure S1 and everything after Figure 13 are excluded.

No source-defined scientific thresholds, regression methods, FDR procedure,
bootstrap settings, AAO thresholds, lag definitions, Qnet* definition, sector
definitions, processed-output file names, or latest final plotting logic are
intentionally changed.

"""

# 1. MOUNT GOOGLE DRIVE

try:
    from google.colab import drive

    drive.mount("/content/drive")

except Exception:
    print(
        "Google Drive mounting skipped because "
        "this is not Google Colab."
    )


# 2. INSTALL REQUIRED PACKAGES
import importlib.util
import subprocess
import sys

REQUIRED_PACKAGES = {
    "numpy": "numpy",
    "pandas": "pandas",
    "xarray": "xarray",
    "matplotlib": "matplotlib",
    "scipy": "scipy",
    "statsmodels": "statsmodels",
    "cartopy": "cartopy",
    "netCDF4": "netCDF4",
    "h5netcdf": "h5netcdf",
}

missing_packages = [
    pip_name
    for import_name, pip_name in REQUIRED_PACKAGES.items()
    if importlib.util.find_spec(import_name) is None
]

if missing_packages:
    print(
        "Installing missing packages:",
        ", ".join(missing_packages),
    )

    subprocess.check_call(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "-q",
            *missing_packages,
        ]
    )

    print(
        "Package installation completed."
    )

else:
    print(
        "All required packages are already installed."
    )


# 3. IMPORT LIBRARIES

import gc
import os
import warnings

from collections import OrderedDict
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

import matplotlib

# Use the non-interactive backend retained by the low-RAM source workflow.
matplotlib.use("Agg")

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.dates as mdates

from matplotlib.path import Path as MplPath
from matplotlib.patches import Patch

from scipy.stats import pearsonr
from scipy.stats import t as student_t
from scipy.stats import zscore

import statsmodels.api as sm

from statsmodels.stats.multitest import multipletests
from statsmodels.stats.outliers_influence import (
    variance_inflation_factor,
)

import cartopy.crs as ccrs

warnings.filterwarnings(
    "ignore",
    category=RuntimeWarning,
)


# PART A — LATEST FIGURE 13 SCIENCE: LOW-RAM WSC MASK FIX
# The following processing is taken from the later Figure 13 low-RAM workflow
# explicitly labelled "WSC MASK FIX".
#
# Its own superseded plotting helpers/rendering are not included.

# FIGURE 13 — LOCAL FORCING AND AAO ATTRIBUTION
# LOW-RAM, CHECKPOINTED, 1080-DPI WORKFLOW — WSC MASK FIX
#
# This version is designed for Google Colab sessions that crashed when:
#   • many large NetCDF files remained open simultaneously;
#   • Qnet* and wind-stress curl were created as complete 3-D arrays;
#   • hundreds of bootstrap composite maps were stored in memory;
#   • a very large physical figure was rendered at 1080 dpi.
#
# LOW-RAM STRATEGY
# 1. Process ONE NetCDF variable at a time.
# 2. Load ONE monthly 2-D field at a time.
# 3. Immediately reduce each field to 13 area-weighted sector means.
# 4. Close every NetCDF before opening the next one.
# 5. Derive Qnet* month-by-month from SSRD, STRD, SLHF and SSHF.
# 6. Derive wind-stress curl month-by-month from U10 and V10.
# 7. Save each small sector series as a checkpoint CSV.
# 8. Calculate the AAO composite on an automatically coarsened SLA grid.
# 9. Use online bootstrap sign counts; do not store all bootstrap maps.
# 10. Save a compact fixed-size figure at 1080 dpi without bbox_inches="tight".
#
# SCIENTIFIC NOTE ON HEAT FLUX
# The available radiative fields are:
#   SSRD = downward shortwave radiation
#   STRD = downward longwave radiation
#
# They are not net SSR and net STR. Therefore this workflow uses:
#
#   Qnet* = SSRD + STRD + signed(SLHF) + signed(SSHF)
#
# Qnet* is labelled as a SURFACE HEAT-FLUX PROXY throughout the outputs.
# A complete physical net surface heat flux requires ERA5 SSR and STR.
#
# OUTPUT
# /content/drive/MyDrive/SAM_Thesis/paper2/



# 3. PATHS
BASE_DIR = Path("/content/drive/MyDrive/SAM_Thesis")
DATA_DIR = BASE_DIR / "Data"
INVENTORY_DIR = BASE_DIR / "Processed" / "EN4_NetCDF_inventory"
OUTPUT_DIR = BASE_DIR / "paper2"
CACHE_DIR = OUTPUT_DIR / "Fig13_lowRAM_cache"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)

FILE_PATHS = {
    # Response variables
    "sla": DATA_DIR / "SLA_Antarctic_monthly_2008_2025.nc",
    "total_steric": INVENTORY_DIR / "EN4_total_steric_0_1000m_monthly_2008_2025_SO.nc",
    "thermosteric": INVENTORY_DIR / "EN4_thermosteric_0_1000m_monthly_2008_2025_SO.nc",
    "halosteric": INVENTORY_DIR / "EN4_halosteric_0_1000m_monthly_2008_2025_SO.nc",

    # Thermosteric drivers
    "ohc": INVENTORY_DIR / "EN4_OHC_0_1000m_monthly_2008_2025_SO.nc",
    "sst": DATA_DIR / "OSTIA_SST_monthly_2008_2025_SO.nc",
    "radiative_flux": DATA_DIR / "SW_LW_era.nc",
    "turbulent_flux": DATA_DIR / "heatflux_latent_sensible_era.nc",
    "wind_uv": DATA_DIR / "Wind_U_V_era.nc",
    "mld": DATA_DIR / "MLD_monthly_2008_2025_SO.nc",
    "sic": DATA_DIR / "OSTIA_sea_ice_fraction_monthly_2008_2025_SO.nc",

    # Halosteric drivers
    "fwc": INVENTORY_DIR / "EN4_freshwater_content_0_200m_monthly_2008_2025_SO.nc",
    "sss_anomaly": INVENTORY_DIR / "EN4_surface_salinity_anomaly_0_30m_monthly_2008_2025_SO.nc",
    "snowfall": DATA_DIR / "P_Snow_era.nc",
    "stratification": INVENTORY_DIR / "EN4_stratification_20_200m_monthly_2008_2025_SO.nc",

    # Background and climate index
    "gebco": DATA_DIR / "GEBCO_2024_CF.nc",
    "aao": DATA_DIR / "NOAA_CPC_SAM_AAO_monthly_2008_2025.nc",
}

OUT_SECTOR_TS = OUTPUT_DIR / "Fig13_sector_driver_timeseries_LOW_RAM.csv"

OUT_TABLE_A = OUTPUT_DIR / "Fig13a_SLA_steric_correlations.csv"
OUT_TABLE_B = OUTPUT_DIR / "Fig13b_thermosteric_driver_correlations.csv"
OUT_TABLE_C = OUTPUT_DIR / "Fig13c_halosteric_driver_correlations.csv"
OUT_TABLE_D = OUTPUT_DIR / "Fig13d_thermosteric_regression_coefficients.csv"
OUT_TABLE_E = OUTPUT_DIR / "Fig13e_halosteric_regression_coefficients.csv"
OUT_TABLE_G = OUTPUT_DIR / "Fig13g_AAO_SLA_lag_correlations.csv"

OUT_COMPOSITE = OUTPUT_DIR / "Fig13h_AAO_SLA_composite_LOW_RAM.nc"


# 4. USER-CONTROLLED LOW-RAM SETTINGS
REUSE_CACHED_SECTOR_SERIES = True
REUSE_CACHED_COMPOSITE = True

# ERA5 monthly means of accumulated fields in J m-2 are divided by
# 86400 seconds to obtain W m-2.
ERA5_ACCUMULATION_DIVISOR_SECONDS = 86400.0

# Native ERA5 accumulated SLHF and SSHF are normally signed with
# downward positive; upward ocean heat loss is negative.
#
# "ecmwf_native" = add SLHF and SSHF directly.
# "reverse"      = reverse both turbulent-flux signs before addition.
TURBULENT_FLUX_SIGN_MODE = "ecmwf_native"

# Bulk wind-stress calculation constants
AIR_DENSITY_KG_M3 = 1.225
EARTH_RADIUS_M = 6_371_000.0

# The SLA composite and bootstrap are calculated on a coarsened grid.
# Factor 2 substantially reduces RAM and bootstrap runtime while retaining
# the broad circumpolar composite pattern.
COMPOSITE_COARSEN_FACTOR = 2
COMPOSITE_BOOTSTRAP_REPLICATES = 250
COMPOSITE_BOOTSTRAP_SEED = 42

# High-resolution export
SAVE_DPI = 1080

# Compact physical size limits PNG rendering memory:
# about 9.0 × 5.9 inches at 1080 dpi.
FIGSIZE = (9.0, 5.9)

LAT_MIN = -90.0
LAT_MAX = -60.0
LON_MIN = -180.0
LON_MAX = 180.0

AAO_POSITIVE_THRESHOLD = 1.0
AAO_NEGATIVE_THRESHOLD = -1.0
LAGS = np.arange(-6, 7, dtype=int)

HEAT_FLUX_KEY = "Qnet*"


# 5. FIGURE STYLE
FONT_PANEL = 7.4
FONT_AXIS = 5.8
FONT_TICK = 4.8
FONT_CELL = 4.0
FONT_NOTE = 5.0
FONT_MAP = 4.7
FONT_LEGEND = 4.9

CORR_CMAP = plt.get_cmap("coolwarm")
CORR_NORM = mcolors.TwoSlopeNorm(vmin=-1.0, vcenter=0.0, vmax=1.0)

COEF_CMAP = plt.get_cmap("coolwarm")
COEF_NORM = mcolors.TwoSlopeNorm(vmin=-1.0, vcenter=0.0, vmax=1.0)

plt.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.weight": "bold",
        "axes.titleweight": "bold",
        "axes.labelweight": "bold",
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "savefig.facecolor": "white",
        "savefig.edgecolor": "none",
    }
)


# 6. 13 ANTARCTIC SHELF SECTORS
SEA_SECTORS = OrderedDict([
    ("WED", {"name": "Weddell Sea",         "lon_min":  -60.0, "lon_max":  -20.0}),
    ("KHV", {"name": "King Haakon VII Sea", "lon_min":  -20.0, "lon_max":   10.0}),
    ("RLS", {"name": "Riiser-Larsen Sea",   "lon_min":   10.0, "lon_max":   35.0}),
    ("LAZ", {"name": "Lazarev Sea",         "lon_min":   35.0, "lon_max":   60.0}),
    ("COS", {"name": "Cosmonauts Sea",      "lon_min":   60.0, "lon_max":   90.0}),
    ("COO", {"name": "Cooperation Sea",     "lon_min":   90.0, "lon_max":  115.0}),
    ("DAV", {"name": "Davis Sea",           "lon_min":  115.0, "lon_max":  130.0}),
    ("MAW", {"name": "Mawson Sea",          "lon_min":  130.0, "lon_max":  150.0}),
    ("DUR", {"name": "D'Urville Sea",       "lon_min":  150.0, "lon_max":  170.0}),
    ("SOM", {"name": "Somov Sea",           "lon_min":  170.0, "lon_max": -160.0}),
    ("ROS", {"name": "Ross Sea",            "lon_min": -160.0, "lon_max": -130.0}),
    ("AMU", {"name": "Amundsen Sea",        "lon_min": -130.0, "lon_max": -100.0}),
    ("BEL", {"name": "Bellingshausen Sea",  "lon_min": -100.0, "lon_max":  -60.0}),
])

SEA_ORDER = list(SEA_SECTORS.keys())

THERMO_DRIVER_ORDER = [
    "OHC",
    "SST",
    HEAT_FLUX_KEY,
    "WSC",
    "MLD",
    "SIC",
    "AAO",
]

HALO_DRIVER_ORDER = [
    "FWC",
    "SSS anomaly",
    "SIC",
    "Snowfall",
    "MLD",
    "Stratification",
    "AAO",
]

THERMO_REG_ORDER = [
    HEAT_FLUX_KEY,
    "WSC",
    "MLD",
    "SIC",
    "AAO",
]

HALO_REG_ORDER = [
    "FWC",
    "SIC",
    "Snowfall",
    "MLD",
    "AAO",
]


# 7. GENERIC FILE / COORDINATE HELPERS
def require_file(path, label):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"{label} file not found:\n{path}")
    return path


def open_dataset_safely(path):
    attempts = []

    for engine in [None, "netcdf4", "h5netcdf", "scipy"]:
        try:
            kwargs = {
                "decode_times": True,
                "mask_and_scale": True,
                "cache": False,
            }

            if engine is not None:
                kwargs["engine"] = engine

            dataset = xr.open_dataset(path, **kwargs)

            print(
                f"Opened {Path(path).name} with "
                f"engine={engine or 'xarray-default'}"
            )

            return dataset

        except Exception as error:
            attempts.append(f"{engine}: {error}")

    raise RuntimeError(
        f"Could not open:\n{path}\n\n"
        + "\n".join(attempts)
    )


def detect_coordinate(dataset, kind):
    aliases = {
        "lat": ["lat", "latitude", "nav_lat", "y"],
        "lon": ["lon", "longitude", "nav_lon", "x"],
        "time": ["time", "valid_time", "date", "month", "datetime"],
    }

    for name in list(dataset.coords) + list(dataset.variables):
        variable = dataset[name]

        lower_name = name.lower()
        standard_name = str(
            variable.attrs.get("standard_name", "")
        ).lower()
        axis = str(variable.attrs.get("axis", "")).upper()
        units = str(variable.attrs.get("units", "")).lower()

        if kind == "lat":
            if (
                lower_name in aliases["lat"]
                or standard_name == "latitude"
                or axis == "Y"
                or "degrees_north" in units
            ):
                return name

        elif kind == "lon":
            if (
                lower_name in aliases["lon"]
                or standard_name == "longitude"
                or axis == "X"
                or "degrees_east" in units
            ):
                return name

        elif kind == "time":
            if (
                lower_name in aliases["time"]
                or axis == "T"
                or np.issubdtype(variable.dtype, np.datetime64)
            ):
                return name

    raise KeyError(f"Could not detect {kind} coordinate.")


def standardize_dataset(dataset):
    latitude_name = detect_coordinate(dataset, "lat")
    longitude_name = detect_coordinate(dataset, "lon")

    rename_mapping = {}

    if latitude_name != "lat":
        rename_mapping[latitude_name] = "lat"

    if longitude_name != "lon":
        rename_mapping[longitude_name] = "lon"

    try:
        time_name = detect_coordinate(dataset, "time")
        if time_name != "time":
            rename_mapping[time_name] = "time"
    except Exception:
        pass

    if rename_mapping:
        dataset = dataset.rename(rename_mapping)

    normalized_longitude = (
        (dataset["lon"].astype(float) + 180.0) % 360.0
    ) - 180.0

    dataset = dataset.assign_coords(lon=normalized_longitude)

    longitude_values = np.asarray(dataset["lon"].values)
    _, unique_indices = np.unique(longitude_values, return_index=True)

    dataset = dataset.isel(lon=np.sort(unique_indices))
    dataset = dataset.sortby("lon").sortby("lat")

    if "time" in dataset.coords:
        month_start = (
            pd.DatetimeIndex(pd.to_datetime(dataset["time"].values))
            .to_period("M")
            .to_timestamp()
        )

        dataset = dataset.assign_coords(time=month_start)

        if month_start.duplicated().any():
            dataset = dataset.groupby("time").mean(skipna=True)

        dataset = dataset.sortby("time")

    return dataset


def reduce_extra_dimensions(data_array):
    allowed = {"time", "lat", "lon"}

    for dimension in list(data_array.dims):
        if dimension in allowed:
            continue

        size = data_array.sizes[dimension]

        if size == 1:
            data_array = data_array.isel({dimension: 0}, drop=True)

        elif dimension.lower() in {"expver", "number", "ensemble"}:
            data_array = data_array.mean(dimension, skipna=True)

        else:
            print(
                f"WARNING: selecting index 0 from unexpected "
                f"dimension {dimension!r}, size={size}."
            )
            data_array = data_array.isel({dimension: 0}, drop=True)

    return data_array


def prepare_monthly_field(data_array):
    data_array = reduce_extra_dimensions(data_array)

    data_array = data_array.sel(
        time=slice("2008-01-01", "2025-12-31"),
        lat=slice(LAT_MIN, LAT_MAX),
    )

    return data_array.transpose("time", "lat", "lon")


def detect_variable(dataset, exact_names, include_tokens, label):
    lower_to_original = {
        variable_name.lower(): variable_name
        for variable_name in dataset.data_vars
    }

    for candidate in exact_names:
        if candidate.lower() in lower_to_original:
            selected = lower_to_original[candidate.lower()]
            print(f"Detected {label}: {selected}")
            return selected

    scored = []

    for variable_name in dataset.data_vars:
        data_array = dataset[variable_name]

        if not {"time", "lat", "lon"}.issubset(set(data_array.dims)):
            continue

        name_lower = variable_name.lower()
        long_name = str(data_array.attrs.get("long_name", "")).lower()
        standard_name = str(
            data_array.attrs.get("standard_name", "")
        ).lower()

        score = 0

        for token in include_tokens:
            token = token.lower()

            if token in name_lower:
                score += 12

            if token in long_name:
                score += 5

            if token in standard_name:
                score += 5

        if score > 0:
            scored.append((score, variable_name))

    if not scored:
        raise KeyError(
            f"Could not detect {label}.\n"
            f"Available variables: {list(dataset.data_vars)}"
        )

    scored.sort(reverse=True)
    selected = scored[0][1]

    print(f"Detected {label}: {selected}")
    return selected


def height_scale_to_cm(data_array):
    units = str(data_array.attrs.get("units", "")).lower().strip()

    if units in {
        "m",
        "meter",
        "meters",
        "metre",
        "metres",
    }:
        return 100.0

    return 1.0


# 8. GEBCO OCEAN MASK
def load_reduced_gebco():
    path = require_file(FILE_PATHS["gebco"], "GEBCO")

    dataset = standardize_dataset(
        open_dataset_safely(path)
    )

    variable_name = detect_variable(
        dataset,
        ["elevation", "z", "depth", "Band1"],
        ["elevation", "bathymetry", "depth"],
        "GEBCO elevation",
    )

    elevation = dataset[variable_name].sel(
        lat=slice(LAT_MIN, LAT_MAX)
    )

    latitude_step = max(
        1,
        int(np.ceil(elevation.sizes["lat"] / 420)),
    )

    longitude_step = max(
        1,
        int(np.ceil(elevation.sizes["lon"] / 840)),
    )

    elevation = elevation.isel(
        lat=slice(None, None, latitude_step),
        lon=slice(None, None, longitude_step),
    ).load()

    dataset.close()

    print(
        "Reduced GEBCO grid:",
        dict(elevation.sizes),
    )

    return elevation


def ocean_mask_on_grid(gebco, latitude, longitude):
    bathymetry = gebco.interp(
        lat=latitude,
        lon=longitude,
        method="nearest",
    )

    return np.asarray(
        bathymetry.values < 0.0,
        dtype=bool,
    )


# 9. SECTOR-MEAN HELPERS
def sector_mask(longitude_2d, latitude_2d, lon_min, lon_max):
    latitude_condition = (
        (latitude_2d >= LAT_MIN)
        & (latitude_2d <= LAT_MAX)
    )

    if lon_max < lon_min:
        longitude_condition = (
            (longitude_2d >= lon_min)
            | (longitude_2d < lon_max)
        )
    else:
        longitude_condition = (
            (longitude_2d >= lon_min)
            & (longitude_2d < lon_max)
        )

    return latitude_condition & longitude_condition


def prepare_sector_geometry(latitude, longitude, ocean_mask):
    longitude_2d, latitude_2d = np.meshgrid(
        np.asarray(longitude, dtype=float),
        np.asarray(latitude, dtype=float),
    )

    area_weights = np.cos(
        np.deg2rad(latitude_2d)
    ).astype(np.float32)

    masks = {}

    for sea_code, information in SEA_SECTORS.items():
        masks[sea_code] = (
            sector_mask(
                longitude_2d,
                latitude_2d,
                information["lon_min"],
                information["lon_max"],
            )
            & ocean_mask
        )

    return area_weights, masks


def area_weighted_sector_values(field, area_weights, masks):
    values = {}

    for sea_code in SEA_ORDER:
        valid = (
            masks[sea_code]
            & np.isfinite(field)
        )

        if valid.sum() == 0:
            values[sea_code] = np.nan
            continue

        values[sea_code] = float(
            np.average(
                field[valid],
                weights=area_weights[valid],
            )
        )

    return values


def cache_path(key):
    safe_name = (
        key.replace(" ", "_")
        .replace("*", "star")
        .replace("/", "_")
    )

    return CACHE_DIR / f"{safe_name}_sector_monthly.csv"


def load_cached_sector_table(key):
    path = cache_path(key)

    if not (
        REUSE_CACHED_SECTOR_SERIES
        and path.exists()
    ):
        return None

    table = pd.read_csv(path, parse_dates=["time"])
    table = table.set_index("time").sort_index()

    required_columns = set(SEA_ORDER)

    if not required_columns.issubset(table.columns):
        return None

    print(f"Loaded cached sector series: {path.name}")
    return table[SEA_ORDER]


def save_sector_cache(key, table):
    path = cache_path(key)

    table.to_csv(path, index_label="time")
    print(f"Saved checkpoint: {path.name}")


# 10. STANDARD FIELD → 13 SECTOR SERIES
def process_standard_field(
    key,
    path,
    exact_names,
    include_tokens,
    gebco,
    apply_height_cm_conversion=False,
):
    cached = load_cached_sector_table(key)

    if cached is not None:
        return cached

    dataset = standardize_dataset(
        open_dataset_safely(path)
    )

    variable_name = detect_variable(
        dataset,
        exact_names,
        include_tokens,
        key,
    )

    data_array = prepare_monthly_field(
        dataset[variable_name]
    )

    scale = (
        height_scale_to_cm(data_array)
        if apply_height_cm_conversion
        else 1.0
    )

    latitude = data_array["lat"].values
    longitude = data_array["lon"].values
    time = pd.DatetimeIndex(data_array["time"].values)

    ocean_mask = ocean_mask_on_grid(
        gebco,
        data_array["lat"],
        data_array["lon"],
    )

    area_weights, masks = prepare_sector_geometry(
        latitude,
        longitude,
        ocean_mask,
    )

    output_rows = []

    print(
        f"Processing {key} month-by-month: "
        f"{data_array.sizes['time']} months"
    )

    for time_index in range(data_array.sizes["time"]):
        field = np.asarray(
            data_array.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze()

        field = field * np.float32(scale)

        values = area_weighted_sector_values(
            field,
            area_weights,
            masks,
        )

        values["time"] = time[time_index]
        output_rows.append(values)

        del field

        if (
            (time_index + 1) % 24 == 0
            or time_index == data_array.sizes["time"] - 1
        ):
            print(
                f"  [{time_index + 1:03d}/"
                f"{data_array.sizes['time']:03d}] "
                f"{time[time_index]:%Y-%m}"
            )

    output = (
        pd.DataFrame(output_rows)
        .set_index("time")
        .sort_index()
    )[SEA_ORDER]

    dataset.close()
    del dataset, data_array, ocean_mask, area_weights, masks
    gc.collect()

    save_sector_cache(key, output)
    return output


# 11. Qnet* PROXY → 13 SECTOR SERIES, MONTH-BY-MONTH
def process_qnet_proxy(gebco):
    cached = load_cached_sector_table(HEAT_FLUX_KEY)

    if cached is not None:
        return cached

    radiative_dataset = standardize_dataset(
        open_dataset_safely(FILE_PATHS["radiative_flux"])
    )

    turbulent_dataset = standardize_dataset(
        open_dataset_safely(FILE_PATHS["turbulent_flux"])
    )

    ssrd_name = detect_variable(
        radiative_dataset,
        ["ssrd"],
        ["ssrd", "short-wave", "shortwave", "solar", "downward"],
        "SSRD",
    )

    strd_name = detect_variable(
        radiative_dataset,
        ["strd"],
        ["strd", "long-wave", "longwave", "thermal", "downward"],
        "STRD",
    )

    slhf_name = detect_variable(
        turbulent_dataset,
        ["slhf"],
        ["slhf", "latent"],
        "SLHF",
    )

    sshf_name = detect_variable(
        turbulent_dataset,
        ["sshf"],
        ["sshf", "sensible"],
        "SSHF",
    )

    ssrd = prepare_monthly_field(radiative_dataset[ssrd_name])
    strd = prepare_monthly_field(radiative_dataset[strd_name])
    slhf = prepare_monthly_field(turbulent_dataset[slhf_name])
    sshf = prepare_monthly_field(turbulent_dataset[sshf_name])

    common_time = (
        pd.Index(pd.DatetimeIndex(ssrd["time"].values))
        .intersection(pd.Index(pd.DatetimeIndex(strd["time"].values)))
        .intersection(pd.Index(pd.DatetimeIndex(slhf["time"].values)))
        .intersection(pd.Index(pd.DatetimeIndex(sshf["time"].values)))
        .sort_values()
    )

    if len(common_time) == 0:
        raise RuntimeError("No common months among Qnet* components.")

    ssrd = ssrd.sel(time=common_time)
    strd = strd.sel(time=common_time)
    slhf = slhf.sel(time=common_time)
    sshf = sshf.sel(time=common_time)

    reference_latitude = ssrd["lat"]
    reference_longitude = ssrd["lon"]

    # Interpolation objects remain lazy; only one monthly field is
    # evaluated inside the loop.
    if not (
        strd.sizes["lat"] == ssrd.sizes["lat"]
        and strd.sizes["lon"] == ssrd.sizes["lon"]
        and np.allclose(strd["lat"], reference_latitude)
        and np.allclose(strd["lon"], reference_longitude)
    ):
        strd = strd.interp(
            lat=reference_latitude,
            lon=reference_longitude,
            method="linear",
        )

    if not (
        slhf.sizes["lat"] == ssrd.sizes["lat"]
        and slhf.sizes["lon"] == ssrd.sizes["lon"]
        and np.allclose(slhf["lat"], reference_latitude)
        and np.allclose(slhf["lon"], reference_longitude)
    ):
        slhf = slhf.interp(
            lat=reference_latitude,
            lon=reference_longitude,
            method="linear",
        )

    if not (
        sshf.sizes["lat"] == ssrd.sizes["lat"]
        and sshf.sizes["lon"] == ssrd.sizes["lon"]
        and np.allclose(sshf["lat"], reference_latitude)
        and np.allclose(sshf["lon"], reference_longitude)
    ):
        sshf = sshf.interp(
            lat=reference_latitude,
            lon=reference_longitude,
            method="linear",
        )

    ocean_mask = ocean_mask_on_grid(
        gebco,
        reference_latitude,
        reference_longitude,
    )

    area_weights, masks = prepare_sector_geometry(
        reference_latitude.values,
        reference_longitude.values,
        ocean_mask,
    )

    turbulent_multiplier = (
        1.0
        if TURBULENT_FLUX_SIGN_MODE == "ecmwf_native"
        else -1.0
    )

    output_rows = []

    print(
        "Processing Qnet* month-by-month:\n"
        "  Qnet* = SSRD + STRD + signed(SLHF) + signed(SSHF)"
    )

    for time_index, timestamp in enumerate(common_time):
        sw = np.asarray(
            ssrd.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze() / np.float32(ERA5_ACCUMULATION_DIVISOR_SECONDS)

        lw = np.asarray(
            strd.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze() / np.float32(ERA5_ACCUMULATION_DIVISOR_SECONDS)

        latent = np.asarray(
            slhf.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze() / np.float32(ERA5_ACCUMULATION_DIVISOR_SECONDS)

        sensible = np.asarray(
            sshf.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze() / np.float32(ERA5_ACCUMULATION_DIVISOR_SECONDS)

        heat_flux_proxy = (
            sw
            + lw
            + np.float32(turbulent_multiplier) * latent
            + np.float32(turbulent_multiplier) * sensible
        )

        heat_flux_proxy[~ocean_mask] = np.nan

        values = area_weighted_sector_values(
            heat_flux_proxy,
            area_weights,
            masks,
        )

        values["time"] = pd.Timestamp(timestamp)
        output_rows.append(values)

        del sw, lw, latent, sensible, heat_flux_proxy

        if (
            (time_index + 1) % 24 == 0
            or time_index == len(common_time) - 1
        ):
            print(
                f"  [{time_index + 1:03d}/"
                f"{len(common_time):03d}] "
                f"{pd.Timestamp(timestamp):%Y-%m}"
            )

    output = (
        pd.DataFrame(output_rows)
        .set_index("time")
        .sort_index()
    )[SEA_ORDER]

    radiative_dataset.close()
    turbulent_dataset.close()

    del (
        radiative_dataset,
        turbulent_dataset,
        ssrd,
        strd,
        slhf,
        sshf,
        ocean_mask,
        area_weights,
        masks,
    )

    gc.collect()

    save_sector_cache(HEAT_FLUX_KEY, output)
    return output


# 12. WIND-STRESS CURL → 13 SECTOR SERIES, MONTH-BY-MONTH
def process_wind_stress_curl(gebco):
    key = "WSC"

    cached = load_cached_sector_table(key)

    if cached is not None:
        return cached

    dataset = standardize_dataset(
        open_dataset_safely(FILE_PATHS["wind_uv"])
    )

    u_name = detect_variable(
        dataset,
        ["u10", "10u", "u_wind", "u"],
        ["u10", "zonal", "u_component"],
        "10 m zonal wind",
    )

    v_name = detect_variable(
        dataset,
        ["v10", "10v", "v_wind", "v"],
        ["v10", "meridional", "v_component"],
        "10 m meridional wind",
    )

    u = prepare_monthly_field(dataset[u_name])
    v = prepare_monthly_field(dataset[v_name])

    common_time = (
        pd.Index(pd.DatetimeIndex(u["time"].values))
        .intersection(pd.Index(pd.DatetimeIndex(v["time"].values)))
        .sort_values()
    )

    u = u.sel(time=common_time)
    v = v.sel(time=common_time)

    if not (
        v.sizes["lat"] == u.sizes["lat"]
        and v.sizes["lon"] == u.sizes["lon"]
        and np.allclose(v["lat"], u["lat"])
        and np.allclose(v["lon"], u["lon"])
    ):
        v = v.interp(
            lat=u["lat"],
            lon=u["lon"],
            method="linear",
        )

    latitude = np.asarray(u["lat"].values, dtype=np.float64)
    longitude = np.asarray(u["lon"].values, dtype=np.float64)

    ocean_mask = ocean_mask_on_grid(
        gebco,
        u["lat"],
        u["lon"],
    )

    area_weights, masks = prepare_sector_geometry(
        latitude,
        longitude,
        ocean_mask,
    )

    latitude_radians = np.deg2rad(latitude)

    # Keep the latitude factor as a broadcastable (lat, 1) array.
    # At/near the South Pole, cos(latitude) approaches zero. Replacing
    # those rows with NaN before division avoids both singular values
    # and the previous boolean-index shape mismatch.
    cosine_latitude_1d = np.cos(latitude_radians)

    safe_cosine_latitude = np.where(
        np.abs(cosine_latitude_1d) < 0.02,
        np.nan,
        cosine_latitude_1d,
    )[:, None].astype(np.float64)

    longitude_spacing = float(
        np.nanmedian(np.diff(np.deg2rad(longitude)))
    )

    output_rows = []

    print("Processing wind-stress curl month-by-month.")

    for time_index, timestamp in enumerate(common_time):
        u_field = np.asarray(
            u.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze()

        v_field = np.asarray(
            v.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze()

        speed = np.hypot(u_field, v_field)

        drag = np.where(
            speed <= 11.0,
            1.2e-3,
            np.where(
                speed <= 20.0,
                (0.49 + 0.065 * speed) * 1.0e-3,
                1.8e-3,
            ),
        ).astype(np.float32)

        tau_x = (
            np.float32(AIR_DENSITY_KG_M3)
            * drag
            * speed
            * u_field
        )

        tau_y = (
            np.float32(AIR_DENSITY_KG_M3)
            * drag
            * speed
            * v_field
        )

        # Periodic central difference in longitude.
        d_tau_y_d_lambda = (
            np.roll(tau_y, -1, axis=1)
            - np.roll(tau_y, 1, axis=1)
        ) / np.float32(2.0 * longitude_spacing)

        # Non-periodic gradient in latitude.
        d_tau_x_d_phi = np.gradient(
            tau_x,
            latitude_radians,
            axis=0,
            edge_order=1,
        )

        with np.errstate(divide="ignore", invalid="ignore"):
            curl = (
                d_tau_y_d_lambda
                / (
                    np.float64(EARTH_RADIUS_M)
                    * safe_cosine_latitude
                )
                - d_tau_x_d_phi
                / np.float64(EARTH_RADIUS_M)
            )

        # Ensure a normal writable 2-D array before masking.
        curl = np.asarray(
            curl,
            dtype=np.float32,
        )

        # Rows close to 90°S are already NaN through
        # safe_cosine_latitude broadcasting. Apply only the full
        # two-dimensional ocean mask here.
        curl[~ocean_mask] = np.nan

        values = area_weighted_sector_values(
            curl,
            area_weights,
            masks,
        )

        values["time"] = pd.Timestamp(timestamp)
        output_rows.append(values)

        del (
            u_field,
            v_field,
            speed,
            drag,
            tau_x,
            tau_y,
            d_tau_y_d_lambda,
            d_tau_x_d_phi,
            curl,
        )

        if (
            (time_index + 1) % 24 == 0
            or time_index == len(common_time) - 1
        ):
            print(
                f"  [{time_index + 1:03d}/"
                f"{len(common_time):03d}] "
                f"{pd.Timestamp(timestamp):%Y-%m}"
            )

    output = (
        pd.DataFrame(output_rows)
        .set_index("time")
        .sort_index()
    )[SEA_ORDER]

    dataset.close()

    del (
        dataset,
        u,
        v,
        ocean_mask,
        area_weights,
        masks,
        cosine_latitude_1d,
        safe_cosine_latitude,
    )

    gc.collect()

    save_sector_cache(key, output)
    return output


# 13. AAO READER
def read_aao():
    path = require_file(FILE_PATHS["aao"], "AAO")

    if path.suffix.lower() in {".nc", ".nc4", ".cdf"}:
        dataset = open_dataset_safely(path)

        time_name = None

        for candidate in ["time", "valid_time", "date", "month"]:
            if candidate in dataset.coords:
                time_name = candidate
                break

        if time_name is None:
            for coordinate_name in dataset.coords:
                if np.issubdtype(
                    dataset[coordinate_name].dtype,
                    np.datetime64,
                ):
                    time_name = coordinate_name
                    break

        if time_name is None:
            raise KeyError("Could not detect AAO time coordinate.")

        preferred_variables = [
            "AAO",
            "aao",
            "SAM",
            "sam",
            "AAO_index",
            "SAM_index",
            "index",
        ]

        value_name = None

        for candidate in preferred_variables:
            if candidate in dataset.data_vars:
                value_name = candidate
                break

        if value_name is None:
            candidates = [
                name
                for name in dataset.data_vars
                if time_name in dataset[name].dims
            ]

            if not candidates:
                raise KeyError(
                    "Could not detect AAO variable.\n"
                    f"Available variables: {list(dataset.data_vars)}"
                )

            value_name = candidates[0]

        values = dataset[value_name]

        for dimension in list(values.dims):
            if dimension == time_name:
                continue

            values = values.isel({dimension: 0}, drop=True)

        time = (
            pd.DatetimeIndex(
                pd.to_datetime(values[time_name].values)
            )
            .to_period("M")
            .to_timestamp()
        )

        output = pd.DataFrame(
            {
                "time": time,
                "AAO": np.asarray(
                    values.values,
                    dtype=float,
                ).reshape(-1),
            }
        )

        dataset.close()

    else:
        dataframe = pd.read_csv(path)

        lower_columns = {
            column.lower(): column
            for column in dataframe.columns
        }

        if (
            "year" in lower_columns
            and "month" in lower_columns
        ):
            time = pd.to_datetime(
                {
                    "year": dataframe[lower_columns["year"]],
                    "month": dataframe[lower_columns["month"]],
                    "day": 1,
                }
            )
        else:
            time_column = next(
                (
                    lower_columns[name]
                    for name in ["time", "date", "month"]
                    if name in lower_columns
                ),
                None,
            )

            if time_column is None:
                raise KeyError("Could not detect AAO time column.")

            time = pd.to_datetime(dataframe[time_column])

        value_column = next(
            (
                lower_columns[name]
                for name in [
                    "aao",
                    "sam",
                    "aao_index",
                    "sam_index",
                    "index",
                ]
                if name in lower_columns
            ),
            None,
        )

        if value_column is None:
            numeric_columns = [
                column
                for column in dataframe.columns
                if pd.api.types.is_numeric_dtype(dataframe[column])
                and column.lower() not in {"year", "month"}
            ]

            if not numeric_columns:
                raise KeyError("Could not detect AAO value column.")

            value_column = numeric_columns[0]

        output = pd.DataFrame(
            {
                "time": time,
                "AAO": pd.to_numeric(
                    dataframe[value_column],
                    errors="coerce",
                ),
            }
        )

    output = output.dropna().sort_values("time")

    output["time"] = (
        pd.DatetimeIndex(output["time"])
        .to_period("M")
        .to_timestamp()
    )

    output = (
        output.groupby("time", as_index=False)["AAO"]
        .mean()
        .set_index("time")
    )

    output = output.loc[
        "2008-01-01":"2025-12-01"
    ]

    standard_deviation = output["AAO"].std(ddof=1)

    if not np.isfinite(standard_deviation) or standard_deviation == 0.0:
        raise ValueError("AAO standard deviation is invalid.")

    output["AAO_std"] = (
        output["AAO"] - output["AAO"].mean()
    ) / standard_deviation

    output["AAO_rm3"] = (
        output["AAO_std"]
        .rolling(3, center=True, min_periods=1)
        .mean()
    )

    print(
        f"AAO months: {len(output)}, "
        f"{output.index.min():%Y-%m} to "
        f"{output.index.max():%Y-%m}"
    )

    return output


# 14. DESEASONALIZATION AND STATISTICS
def deseasonalize(dataframe):
    output = dataframe.copy()

    for column in output.columns:
        monthly_climatology = (
            output.groupby(output.index.month)[column]
            .transform("mean")
        )

        output[column] = output[column] - monthly_climatology

    return output


def lag1_autocorrelation(values):
    values = np.asarray(values, dtype=float)
    valid = np.isfinite(values)

    values = values[valid]

    if values.size < 4:
        return 0.0

    x = values[:-1]
    y = values[1:]

    if np.nanstd(x) == 0.0 or np.nanstd(y) == 0.0:
        return 0.0

    return float(np.corrcoef(x, y)[0, 1])


def pearson_ar1_corrected(x, y):
    dataframe = pd.concat([x, y], axis=1).dropna()

    n = len(dataframe)

    if n < 12:
        return np.nan, np.nan, n, np.nan

    x_values = dataframe.iloc[:, 0].values.astype(float)
    y_values = dataframe.iloc[:, 1].values.astype(float)

    if np.std(x_values) == 0.0 or np.std(y_values) == 0.0:
        return np.nan, np.nan, n, np.nan

    correlation = float(pearsonr(x_values, y_values)[0])

    rx = lag1_autocorrelation(x_values)
    ry = lag1_autocorrelation(y_values)

    denominator = 1.0 + rx * ry

    if denominator <= 0.0:
        effective_n = float(n)
    else:
        effective_n = n * (1.0 - rx * ry) / denominator

    effective_n = float(np.clip(effective_n, 3.0, n))

    if abs(correlation) >= 1.0:
        p_value = 0.0
    else:
        statistic = correlation * np.sqrt(
            (effective_n - 2.0)
            / max(1.0e-12, 1.0 - correlation ** 2)
        )

        p_value = float(
            2.0
            * student_t.sf(
                abs(statistic),
                df=max(1.0, effective_n - 2.0),
            )
        )

    return correlation, p_value, n, effective_n


def apply_fdr(table, p_column="p_raw"):
    output = table.copy()

    p_values = output[p_column].values.astype(float)
    valid = np.isfinite(p_values)

    q_values = np.full(len(output), np.nan, dtype=float)

    if valid.sum() > 0:
        _, corrected, _, _ = multipletests(
            p_values[valid],
            method="fdr_bh",
        )

        q_values[valid] = corrected

    output["p_fdr"] = q_values

    output["sig"] = [
        "**"
        if np.isfinite(q) and q < 0.01
        else "*"
        if np.isfinite(q) and q < 0.05
        else "•"
        if np.isfinite(q) and q < 0.10
        else ""
        for q in q_values
    ]

    return output


def correlation_panel(target, drivers, driver_order):
    rows = []

    for sea_code in SEA_ORDER:
        for driver_name in driver_order:
            correlation, p_value, n, effective_n = (
                pearson_ar1_corrected(
                    target[sea_code],
                    drivers[driver_name][sea_code],
                )
            )

            rows.append(
                {
                    "sea": sea_code,
                    "driver": driver_name,
                    "r": correlation,
                    "p_raw": p_value,
                    "n": n,
                    "effective_n": effective_n,
                }
            )

    return apply_fdr(pd.DataFrame(rows))


def calculate_vif(predictors):
    complete = predictors.dropna()

    output = pd.Series(np.nan, index=predictors.columns)

    if len(complete) < predictors.shape[1] + 3:
        return output

    usable_columns = [
        column
        for column in complete.columns
        if complete[column].std(ddof=1) > 0.0
    ]

    if not usable_columns:
        return output

    matrix = sm.add_constant(
        complete[usable_columns]
    ).values

    values = [
        variance_inflation_factor(matrix, index)
        for index in range(1, matrix.shape[1])
    ]

    output.loc[usable_columns] = values
    return output


def standardized_hac_regression(target, predictors):
    complete = pd.concat(
        [target.rename("target"), predictors],
        axis=1,
    ).dropna()

    if len(complete) < max(24, predictors.shape[1] + 6):
        return None

    target_standardized = pd.Series(
        zscore(complete["target"].values),
        index=complete.index,
        name="target",
    )

    predictor_standardized = pd.DataFrame(
        index=complete.index
    )

    for column in predictors.columns:
        values = complete[column].values.astype(float)
        standard_deviation = np.std(values, ddof=1)

        if standard_deviation == 0.0:
            predictor_standardized[column] = np.nan
        else:
            predictor_standardized[column] = (
                values - np.mean(values)
            ) / standard_deviation

    regression_data = pd.concat(
        [target_standardized, predictor_standardized],
        axis=1,
    ).dropna()

    if len(regression_data) < max(24, predictors.shape[1] + 6):
        return None

    design_matrix = sm.add_constant(
        regression_data[predictors.columns]
    )

    model = sm.OLS(
        regression_data["target"],
        design_matrix,
    ).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": 1},
    )

    return model


def regression_panel(target, drivers, predictor_order):
    rows = []

    for sea_code in SEA_ORDER:
        predictors = pd.DataFrame(
            {
                predictor: drivers[predictor][sea_code]
                for predictor in predictor_order
            }
        )

        vif = calculate_vif(predictors)

        model = standardized_hac_regression(
            target[sea_code],
            predictors,
        )

        for predictor in predictor_order:
            if model is None:
                beta = np.nan
                p_value = np.nan
                adjusted_r2 = np.nan
                n = 0
            else:
                beta = float(model.params.get(predictor, np.nan))
                p_value = float(model.pvalues.get(predictor, np.nan))
                adjusted_r2 = float(model.rsquared_adj)
                n = int(model.nobs)

            rows.append(
                {
                    "sea": sea_code,
                    "predictor": predictor,
                    "beta": beta,
                    "p_raw": p_value,
                    "adjusted_r2": adjusted_r2,
                    "vif": float(vif.get(predictor, np.nan)),
                    "n": n,
                }
            )

    return apply_fdr(pd.DataFrame(rows))


def lag_correlation(aao, sla):
    rows = []

    aao_values = aao.values.astype(float)

    for sea_code in SEA_ORDER:
        sla_values = sla[sea_code].values.astype(float)

        for lag in LAGS:
            if lag > 0:
                x = aao_values[:-lag]
                y = sla_values[lag:]

            elif lag < 0:
                x = aao_values[-lag:]
                y = sla_values[:lag]

            else:
                x = aao_values
                y = sla_values

            x_series = pd.Series(x)
            y_series = pd.Series(y)

            correlation, p_value, n, effective_n = (
                pearson_ar1_corrected(
                    x_series,
                    y_series,
                )
            )

            rows.append(
                {
                    "sea": sea_code,
                    "lag": int(lag),
                    "r": correlation,
                    "p_raw": p_value,
                    "n": n,
                    "effective_n": effective_n,
                }
            )

    return apply_fdr(pd.DataFrame(rows))


# 15. LOW-RAM SLA AAO COMPOSITE AND ONLINE YEAR BOOTSTRAP
def coarsened_coordinates(values, factor):
    usable = (len(values) // factor) * factor

    return (
        np.asarray(values[:usable], dtype=float)
        .reshape(-1, factor)
        .mean(axis=1)
    )


def coarsen_nanmean_2d(field, factor):
    if factor <= 1:
        return field.astype(np.float32, copy=False)

    n_latitude = (field.shape[0] // factor) * factor
    n_longitude = (field.shape[1] // factor) * factor

    trimmed = field[:n_latitude, :n_longitude]

    reshaped = trimmed.reshape(
        n_latitude // factor,
        factor,
        n_longitude // factor,
        factor,
    )

    return np.nanmean(
        reshaped,
        axis=(1, 3),
    ).astype(np.float32)


def build_or_load_composite(aao):
    if (
        REUSE_CACHED_COMPOSITE
        and OUT_COMPOSITE.exists()
    ):
        dataset = xr.open_dataset(OUT_COMPOSITE)

        composite = dataset["composite"].load()
        significant = dataset["fdr_significant"].load().astype(bool)

        n_positive = int(dataset.attrs["n_positive_months"])
        n_negative = int(dataset.attrs["n_negative_months"])

        dataset.close()

        print("Loaded cached AAO composite.")
        return composite, significant, n_positive, n_negative

    dataset = standardize_dataset(
        open_dataset_safely(FILE_PATHS["sla"])
    )

    variable_name = detect_variable(
        dataset,
        ["sla", "SLA"],
        ["sla", "sea_level_anomaly"],
        "SLA",
    )

    data_array = prepare_monthly_field(
        dataset[variable_name]
    )

    scale = height_scale_to_cm(data_array)

    common_time = (
        pd.Index(pd.DatetimeIndex(data_array["time"].values))
        .intersection(pd.Index(aao.index))
        .sort_values()
    )

    data_array = data_array.sel(time=common_time)
    aao_common = aao.loc[common_time]

    positive_times = set(
        aao_common.index[
            aao_common["AAO_std"] >= AAO_POSITIVE_THRESHOLD
        ]
    )

    negative_times = set(
        aao_common.index[
            aao_common["AAO_std"] <= AAO_NEGATIVE_THRESHOLD
        ]
    )

    if not positive_times or not negative_times:
        raise RuntimeError(
            "No positive or negative AAO phase months were found."
        )

    factor = COMPOSITE_COARSEN_FACTOR

    latitude = coarsened_coordinates(
        data_array["lat"].values,
        factor,
    )

    longitude = coarsened_coordinates(
        data_array["lon"].values,
        factor,
    )

    shape = (len(latitude), len(longitude))

    positive_years = sorted(
        {timestamp.year for timestamp in positive_times}
    )

    negative_years = sorted(
        {timestamp.year for timestamp in negative_times}
    )

    positive_year_index = {
        year: index
        for index, year in enumerate(positive_years)
    }

    negative_year_index = {
        year: index
        for index, year in enumerate(negative_years)
    }

    positive_sum = np.zeros(
        (len(positive_years),) + shape,
        dtype=np.float32,
    )

    positive_count = np.zeros(
        (len(positive_years),) + shape,
        dtype=np.uint16,
    )

    negative_sum = np.zeros(
        (len(negative_years),) + shape,
        dtype=np.float32,
    )

    negative_count = np.zeros(
        (len(negative_years),) + shape,
        dtype=np.uint16,
    )

    print(
        "Building coarsened AAO SLA composite month-by-month.\n"
        f"  Coarsening factor: {factor}\n"
        f"  Composite grid: {shape}"
    )

    for time_index, timestamp in enumerate(common_time):
        timestamp = pd.Timestamp(timestamp)

        if (
            timestamp not in positive_times
            and timestamp not in negative_times
        ):
            continue

        field = np.asarray(
            data_array.isel(time=time_index).values,
            dtype=np.float32,
        ).squeeze()

        field = field * np.float32(scale)
        field = coarsen_nanmean_2d(field, factor)

        valid = np.isfinite(field)

        if timestamp in positive_times:
            year_index = positive_year_index[timestamp.year]

            positive_sum[year_index][valid] += field[valid]
            positive_count[year_index][valid] += 1

        if timestamp in negative_times:
            year_index = negative_year_index[timestamp.year]

            negative_sum[year_index][valid] += field[valid]
            negative_count[year_index][valid] += 1

        del field, valid

    positive_total_sum = positive_sum.sum(axis=0, dtype=np.float64)
    positive_total_count = positive_count.sum(axis=0, dtype=np.float64)

    negative_total_sum = negative_sum.sum(axis=0, dtype=np.float64)
    negative_total_count = negative_count.sum(axis=0, dtype=np.float64)

    with np.errstate(divide="ignore", invalid="ignore"):
        observed_composite = (
            positive_total_sum
            / positive_total_count
            - negative_total_sum
            / negative_total_count
        )

    observed_composite[
        (positive_total_count == 0)
        | (negative_total_count == 0)
    ] = np.nan

    # Online bootstrap counters: no bootstrap-map cube is retained.
    greater_than_zero = np.zeros(shape, dtype=np.uint16)
    less_than_zero = np.zeros(shape, dtype=np.uint16)
    valid_bootstrap_count = np.zeros(shape, dtype=np.uint16)

    random_generator = np.random.default_rng(
        COMPOSITE_BOOTSTRAP_SEED
    )

    print(
        "Running online year-block bootstrap:\n"
        f"  Replicates: {COMPOSITE_BOOTSTRAP_REPLICATES}"
    )

    positive_sum_float = positive_sum.astype(np.float32)
    positive_count_float = positive_count.astype(np.float32)
    negative_sum_float = negative_sum.astype(np.float32)
    negative_count_float = negative_count.astype(np.float32)

    for bootstrap_index in range(
        COMPOSITE_BOOTSTRAP_REPLICATES
    ):
        sampled_positive = random_generator.integers(
            0,
            len(positive_years),
            size=len(positive_years),
        )

        sampled_negative = random_generator.integers(
            0,
            len(negative_years),
            size=len(negative_years),
        )

        positive_frequency = np.bincount(
            sampled_positive,
            minlength=len(positive_years),
        ).astype(np.float32)

        negative_frequency = np.bincount(
            sampled_negative,
            minlength=len(negative_years),
        ).astype(np.float32)

        bootstrap_positive_sum = np.tensordot(
            positive_frequency,
            positive_sum_float,
            axes=(0, 0),
        )

        bootstrap_positive_count = np.tensordot(
            positive_frequency,
            positive_count_float,
            axes=(0, 0),
        )

        bootstrap_negative_sum = np.tensordot(
            negative_frequency,
            negative_sum_float,
            axes=(0, 0),
        )

        bootstrap_negative_count = np.tensordot(
            negative_frequency,
            negative_count_float,
            axes=(0, 0),
        )

        with np.errstate(divide="ignore", invalid="ignore"):
            bootstrap_composite = (
                bootstrap_positive_sum
                / bootstrap_positive_count
                - bootstrap_negative_sum
                / bootstrap_negative_count
            )

        valid = (
            (bootstrap_positive_count > 0)
            & (bootstrap_negative_count > 0)
            & np.isfinite(bootstrap_composite)
        )

        greater_than_zero[valid] += (
            bootstrap_composite[valid] > 0.0
        )

        less_than_zero[valid] += (
            bootstrap_composite[valid] < 0.0
        )

        valid_bootstrap_count[valid] += 1

        del (
            positive_frequency,
            negative_frequency,
            bootstrap_positive_sum,
            bootstrap_positive_count,
            bootstrap_negative_sum,
            bootstrap_negative_count,
            bootstrap_composite,
            valid,
        )

        if (
            (bootstrap_index + 1) % 50 == 0
            or bootstrap_index
            == COMPOSITE_BOOTSTRAP_REPLICATES - 1
        ):
            print(
                f"  Bootstrap "
                f"{bootstrap_index + 1:03d}/"
                f"{COMPOSITE_BOOTSTRAP_REPLICATES:03d}"
            )

    with np.errstate(divide="ignore", invalid="ignore"):
        probability_positive = (
            greater_than_zero.astype(float) + 1.0
        ) / (
            valid_bootstrap_count.astype(float) + 2.0
        )

        probability_negative = (
            less_than_zero.astype(float) + 1.0
        ) / (
            valid_bootstrap_count.astype(float) + 2.0
        )

        bootstrap_p = (
            2.0
            * np.minimum(
                probability_positive,
                probability_negative,
            )
        )

    bootstrap_p = np.clip(bootstrap_p, 0.0, 1.0)
    bootstrap_p[valid_bootstrap_count == 0] = np.nan

    bootstrap_q = np.full(shape, np.nan, dtype=float)

    finite = np.isfinite(bootstrap_p)

    if finite.sum() > 0:
        _, corrected, _, _ = multipletests(
            bootstrap_p[finite],
            method="fdr_bh",
        )

        bootstrap_q[finite] = corrected

    significant = bootstrap_q < 0.05

    composite_data_array = xr.DataArray(
        observed_composite.astype(np.float32),
        coords={
            "lat": latitude,
            "lon": longitude,
        },
        dims=("lat", "lon"),
        name="composite",
        attrs={
            "long_name": (
                "Positive-minus-negative AAO SLA composite"
            ),
            "units": "cm",
        },
    )

    output_dataset = xr.Dataset(
        {
            "composite": composite_data_array,
            "bootstrap_p": (
                ("lat", "lon"),
                bootstrap_p.astype(np.float32),
            ),
            "bootstrap_q": (
                ("lat", "lon"),
                bootstrap_q.astype(np.float32),
            ),
            "fdr_significant": (
                ("lat", "lon"),
                significant.astype(np.int8),
            ),
        },
        attrs={
            "n_positive_months": len(positive_times),
            "n_negative_months": len(negative_times),
            "coarsen_factor": factor,
            "bootstrap_replicates": COMPOSITE_BOOTSTRAP_REPLICATES,
            "description": (
                "Low-RAM year-block bootstrap AAO SLA composite"
            ),
        },
    )

    encoding = {
        variable_name: {
            "zlib": True,
            "complevel": 4,
        }
        for variable_name in output_dataset.data_vars
    }

    output_dataset.to_netcdf(
        OUT_COMPOSITE,
        encoding=encoding,
    )

    dataset.close()

    del (
        dataset,
        data_array,
        positive_sum,
        positive_count,
        negative_sum,
        negative_count,
        positive_sum_float,
        positive_count_float,
        negative_sum_float,
        negative_count_float,
        greater_than_zero,
        less_than_zero,
        valid_bootstrap_count,
        output_dataset,
    )

    gc.collect()

    return (
        composite_data_array,
        xr.DataArray(
            significant,
            coords={
                "lat": latitude,
                "lon": longitude,
            },
            dims=("lat", "lon"),
        ),
        len(positive_times),
        len(negative_times),
    )


# 17. MAIN PROCESSING
print("=" * 78)
print("FIGURE 13 — LOW-RAM PROCESSING")
print("=" * 78)

if REUSE_CACHED_SECTOR_SERIES:
    print(
        "Checkpoint resume is ON. Previously completed sector CSV files "
        "will be loaded and will NOT be recomputed."
    )
else:
    print(
        "Checkpoint resume is OFF. All sector variables will be recomputed."
    )

for key, path in FILE_PATHS.items():
    require_file(path, key)

gebco = load_reduced_gebco()

# Process one file at a time. Each function closes its NetCDF immediately.
sector_tables = {}

sector_tables["SLA"] = process_standard_field(
    "SLA",
    FILE_PATHS["sla"],
    ["sla", "SLA"],
    ["sla", "sea_level_anomaly"],
    gebco,
    apply_height_cm_conversion=True,
)

sector_tables["Total steric"] = process_standard_field(
    "Total steric",
    FILE_PATHS["total_steric"],
    ["total_steric_height"],
    ["total", "steric"],
    gebco,
    apply_height_cm_conversion=True,
)

sector_tables["Thermosteric"] = process_standard_field(
    "Thermosteric",
    FILE_PATHS["thermosteric"],
    ["thermosteric_height"],
    ["thermosteric"],
    gebco,
    apply_height_cm_conversion=True,
)

sector_tables["Halosteric"] = process_standard_field(
    "Halosteric",
    FILE_PATHS["halosteric"],
    ["halosteric_height"],
    ["halosteric"],
    gebco,
    apply_height_cm_conversion=True,
)

sector_tables["OHC"] = process_standard_field(
    "OHC",
    FILE_PATHS["ohc"],
    ["ocean_heat_content"],
    ["ocean_heat_content", "ohc"],
    gebco,
)

sector_tables["SST"] = process_standard_field(
    "SST",
    FILE_PATHS["sst"],
    ["SST", "sst", "analysed_sst"],
    ["sst", "sea_surface_temperature"],
    gebco,
)

sector_tables[HEAT_FLUX_KEY] = process_qnet_proxy(gebco)

sector_tables["WSC"] = process_wind_stress_curl(gebco)

sector_tables["MLD"] = process_standard_field(
    "MLD",
    FILE_PATHS["mld"],
    ["MLD", "mld"],
    ["mixed_layer_depth", "mld"],
    gebco,
)

sector_tables["SIC"] = process_standard_field(
    "SIC",
    FILE_PATHS["sic"],
    ["SIF", "sic", "sea_ice_fraction"],
    ["sea_ice_fraction", "sic", "sif"],
    gebco,
)

sector_tables["FWC"] = process_standard_field(
    "FWC",
    FILE_PATHS["fwc"],
    ["freshwater_content"],
    ["freshwater_content", "fwc"],
    gebco,
)

sector_tables["SSS anomaly"] = process_standard_field(
    "SSS anomaly",
    FILE_PATHS["sss_anomaly"],
    ["surface_salinity_anomaly"],
    ["surface_salinity_anomaly", "sss"],
    gebco,
)

sector_tables["Snowfall"] = process_standard_field(
    "Snowfall",
    FILE_PATHS["snowfall"],
    ["snowfall", "sf", "P_Snow"],
    ["snowfall", "snow"],
    gebco,
)

sector_tables["Stratification"] = process_standard_field(
    "Stratification",
    FILE_PATHS["stratification"],
    ["stratification_20_200m"],
    ["stratification"],
    gebco,
)

aao = read_aao()

# Determine one exact common monthly sequence.
common_time = pd.Index(aao.index)

for table in sector_tables.values():
    common_time = common_time.intersection(
        pd.Index(table.index)
    )

common_time = common_time.sort_values()

if len(common_time) < 120:
    raise RuntimeError(
        f"Only {len(common_time)} common months remain. "
        "Inspect input time coordinates."
    )

print(
    f"Common analysis months: {len(common_time)}, "
    f"{common_time.min():%Y-%m} to "
    f"{common_time.max():%Y-%m}"
)

for key in sector_tables:
    sector_tables[key] = sector_tables[key].loc[
        common_time,
        SEA_ORDER,
    ]

aao = aao.loc[common_time]

# AAO is identical for all seas.
aao_sector = pd.DataFrame(
    {
        sea_code: aao["AAO_std"].values
        for sea_code in SEA_ORDER
    },
    index=common_time,
)

sector_tables["AAO"] = aao_sector

# Remove each variable's calendar-month climatology.
anomaly_tables = {}

for key, table in sector_tables.items():
    if key == "AAO":
        anomaly_tables[key] = table.copy()
    else:
        anomaly_tables[key] = deseasonalize(table)

# Save the compact combined matrix.
combined = pd.DataFrame(index=common_time)

for key, table in anomaly_tables.items():
    for sea_code in SEA_ORDER:
        combined[f"{sea_code}|{key}"] = table[sea_code]

combined.to_csv(OUT_SECTOR_TS, index_label="time")

# Free non-anomaly versions except AAO.
del sector_tables, combined
gc.collect()


# 18. PANELS (a)–(g): STATISTICS
panel_a = correlation_panel(
    anomaly_tables["SLA"],
    {
        "Total steric": anomaly_tables["Total steric"],
        "Thermosteric": anomaly_tables["Thermosteric"],
        "Halosteric": anomaly_tables["Halosteric"],
    },
    ["Total steric", "Thermosteric", "Halosteric"],
)

panel_b = correlation_panel(
    anomaly_tables["Thermosteric"],
    {
        driver: anomaly_tables[driver]
        for driver in THERMO_DRIVER_ORDER
    },
    THERMO_DRIVER_ORDER,
)

panel_c = correlation_panel(
    anomaly_tables["Halosteric"],
    {
        driver: anomaly_tables[driver]
        for driver in HALO_DRIVER_ORDER
    },
    HALO_DRIVER_ORDER,
)

panel_d = regression_panel(
    anomaly_tables["Thermosteric"],
    {
        predictor: anomaly_tables[predictor]
        for predictor in THERMO_REG_ORDER
    },
    THERMO_REG_ORDER,
)

panel_e = regression_panel(
    anomaly_tables["Halosteric"],
    {
        predictor: anomaly_tables[predictor]
        for predictor in HALO_REG_ORDER
    },
    HALO_REG_ORDER,
)

panel_g = lag_correlation(
    aao["AAO_std"],
    anomaly_tables["SLA"],
)

panel_a.to_csv(OUT_TABLE_A, index=False)
panel_b.to_csv(OUT_TABLE_B, index=False)
panel_c.to_csv(OUT_TABLE_C, index=False)
panel_d.to_csv(OUT_TABLE_D, index=False)
panel_e.to_csv(OUT_TABLE_E, index=False)
panel_g.to_csv(OUT_TABLE_G, index=False)


# 19. PANEL (h): LOW-RAM COMPOSITE
(
    composite,
    composite_significant,
    n_positive,
    n_negative,
) = build_or_load_composite(aao)


# PART B — LATEST FINAL V3 FIGURE 13 PLOTTING
# This is the later source revision:
# "FINAL PLOT-ONLY LAYOUT CORRECTION — CENTERED PANEL H
#  + PARAGRAPH FOOTNOTE".
#
# It reads the processed CSV/NetCDF products generated in Part A and does not
# recompute the scientific analyses.
# =============================================================================

# FIGURE 13 — LOCAL FORCING AND AAO ATTRIBUTION
# FINAL PLOT-ONLY LAYOUT CORRECTION — CENTERED PANEL H + PARAGRAPH FOOTNOTE
#
# LAYOUT:
#   2 columns × 4 rows
#   Row 1: (a) (b)
#   Row 2: (c) (d)
#   Row 3: (e) (f)
#   Row 4: (g) (h)
#
# THIS SCRIPT DOES NOT RECOMPUTE THE SCIENCE.
# It only reads the already processed Figure 13 outputs and rebuilds
# the final figure with:
#   • 2-column × 4-row layout
#   • larger fonts
#   • larger heatmap cell values
#   • larger legends
#   • panel (h) colorbar label restored
#   • improved spacing with no overlap
#
# Output:
#   Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH_1080dpi.png
#   Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH.pdf


# 3. PATHS
BASE_DIR = Path("/content/drive/MyDrive/SAM_Thesis")
DATA_DIR = BASE_DIR / "Data"
OUTPUT_DIR = BASE_DIR / "paper2"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FILE_A = OUTPUT_DIR / "Fig13a_SLA_steric_correlations.csv"
FILE_B = OUTPUT_DIR / "Fig13b_thermosteric_driver_correlations.csv"
FILE_C = OUTPUT_DIR / "Fig13c_halosteric_driver_correlations.csv"
FILE_D = OUTPUT_DIR / "Fig13d_thermosteric_regression_coefficients.csv"
FILE_E = OUTPUT_DIR / "Fig13e_halosteric_regression_coefficients.csv"
FILE_G = OUTPUT_DIR / "Fig13g_AAO_SLA_lag_correlations.csv"
FILE_SECTOR_TS = OUTPUT_DIR / "Fig13_sector_driver_timeseries_LOW_RAM.csv"
FILE_COMPOSITE = OUTPUT_DIR / "Fig13h_AAO_SLA_composite_LOW_RAM.nc"

GEBCO_CANDIDATES = [
    DATA_DIR / "GEBCO_2024_CF.nc",
    DATA_DIR / "GEBCO_2024_CEC.nc",
]

OUT_PNG = OUTPUT_DIR / "Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH_1080dpi.png"
OUT_PDF = OUTPUT_DIR / "Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH.pdf"
OUT_LOG = OUTPUT_DIR / "Figure13_local_forcing_AAO_2COL4ROW_FINAL_V3_centeredH_log.txt"


# 4. CHECK INPUTS
required_files = [
    FILE_A, FILE_B, FILE_C, FILE_D, FILE_E,
    FILE_G, FILE_SECTOR_TS, FILE_COMPOSITE
]

missing_files = [f for f in required_files if not f.exists()]

if missing_files:
    raise FileNotFoundError(
        "Missing processed Figure 13 files:\n"
        + "\n".join(str(f) for f in missing_files)
    )

GEBCO_FILE = None
for candidate in GEBCO_CANDIDATES:
    if candidate.exists():
        GEBCO_FILE = candidate
        break

if GEBCO_FILE is None:
    raise FileNotFoundError(
        "No GEBCO file found. Checked:\n"
        + "\n".join(str(p) for p in GEBCO_CANDIDATES)
    )


# 5. FIGURE SETTINGS
SAVE_DPI = 1080
FIGSIZE = (11.3, 15.9)
LAT_MIN = -90.0
LAT_MAX = -60.0
LON_MIN = -180.0
LON_MAX = 180.0

FONT_PANEL_TITLE = 14.2
FONT_COLUMN = 9.8
FONT_AXIS = 10.8
FONT_TICK = 8.9
FONT_CELL = 7.8
FONT_CELL_LAG = 6.9
FONT_NOTE = 9.6
FONT_LEGEND = 9.1
FONT_MAP = 8.5
FONT_STATS_BOX = 9.0

plt.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.weight": "bold",
        "axes.titleweight": "bold",
        "axes.labelweight": "bold",
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "savefig.facecolor": "white",
        "savefig.edgecolor": "none",
    }
)

CORR_CMAP = plt.get_cmap("coolwarm")
COEF_CMAP = plt.get_cmap("coolwarm")
CORR_NORM = mcolors.TwoSlopeNorm(vmin=-1.0, vcenter=0.0, vmax=1.0)
COEF_NORM = mcolors.TwoSlopeNorm(vmin=-1.0, vcenter=0.0, vmax=1.0)


# 6. SEA ORDER AND COLUMN LABELS
SEA_SECTORS = OrderedDict([
    ("WED", {"lon_min":  -60.0, "lon_max":  -20.0}),
    ("KHV", {"lon_min":  -20.0, "lon_max":   10.0}),
    ("RLS", {"lon_min":   10.0, "lon_max":   35.0}),
    ("LAZ", {"lon_min":   35.0, "lon_max":   60.0}),
    ("COS", {"lon_min":   60.0, "lon_max":   90.0}),
    ("COO", {"lon_min":   90.0, "lon_max":  115.0}),
    ("DAV", {"lon_min":  115.0, "lon_max":  130.0}),
    ("MAW", {"lon_min":  130.0, "lon_max":  150.0}),
    ("DUR", {"lon_min":  150.0, "lon_max":  170.0}),
    ("SOM", {"lon_min":  170.0, "lon_max": -160.0}),
    ("ROS", {"lon_min": -160.0, "lon_max": -130.0}),
    ("AMU", {"lon_min": -130.0, "lon_max": -100.0}),
    ("BEL", {"lon_min": -100.0, "lon_max":  -60.0}),
])

SEA_ORDER = list(SEA_SECTORS.keys())

PANEL_A_COLUMNS = ["Total steric", "Thermosteric", "Halosteric"]
PANEL_B_COLUMNS = ["OHC", "SST", "Qnet*", "WSC", "MLD", "SIC", "AAO"]
PANEL_C_COLUMNS = ["FWC", "SSS anomaly", "SIC", "Snowfall", "MLD", "Stratification", "AAO"]
PANEL_D_COLUMNS = ["Qnet*", "WSC", "MLD", "SIC", "AAO"]
PANEL_E_COLUMNS = ["FWC", "SIC", "Snowfall", "MLD", "AAO"]
LAGS = np.arange(-6, 7, dtype=int)


# 7. READ PRECOMPUTED OUTPUTS
print("Reading processed Figure 13 outputs only...")

panel_a = pd.read_csv(FILE_A)
panel_b = pd.read_csv(FILE_B)
panel_c = pd.read_csv(FILE_C)
panel_d = pd.read_csv(FILE_D)
panel_e = pd.read_csv(FILE_E)
panel_g = pd.read_csv(FILE_G)

sector_time_series = pd.read_csv(
    FILE_SECTOR_TS,
    parse_dates=["time"]
).set_index("time").sort_index()

composite_dataset = xr.open_dataset(FILE_COMPOSITE)
composite = composite_dataset["composite"].load()

significance_var = "fdr_significant" if "fdr_significant" in composite_dataset.data_vars else "significant"
composite_significant = composite_dataset[significance_var].load().astype(bool)

n_positive = int(
    composite_dataset.attrs.get(
        "n_positive_months",
        composite_dataset.attrs.get("n_positive", 0)
    )
)

n_negative = int(
    composite_dataset.attrs.get(
        "n_negative_months",
        composite_dataset.attrs.get("n_negative", 0)
    )
)

composite_dataset.close()


# 8. AAO TIME SERIES
preferred_aao_column = "WED|AAO"

if preferred_aao_column in sector_time_series.columns:
    aao_column = preferred_aao_column
else:
    candidates = [
        c for c in sector_time_series.columns
        if c.endswith("|AAO") or c.lower() == "aao"
    ]
    if not candidates:
        raise KeyError("No AAO column found in the processed sector time-series file.")
    aao_column = candidates[0]

aao_standardized = pd.to_numeric(sector_time_series[aao_column], errors="coerce")
aao_running_mean = aao_standardized.rolling(window=3, center=True, min_periods=1).mean()


# 9. GEBCO FOR PANEL (h)
def open_gebco(path):
    attempts = []
    for engine in [None, "netcdf4", "h5netcdf", "scipy"]:
        try:
            kwargs = dict(decode_times=True, mask_and_scale=True, cache=False)
            if engine is not None:
                kwargs["engine"] = engine
            return xr.open_dataset(path, **kwargs)
        except Exception as error:
            attempts.append(f"{engine}: {error}")
    raise RuntimeError(
        f"Could not open GEBCO:\n{path}\n" + "\n".join(attempts)
    )

gebco_dataset = open_gebco(GEBCO_FILE)

lat_name = "lat" if "lat" in gebco_dataset.coords else "latitude"
lon_name = "lon" if "lon" in gebco_dataset.coords else "longitude"

if "elevation" in gebco_dataset.data_vars:
    gebco_var = "elevation"
elif "z" in gebco_dataset.data_vars:
    gebco_var = "z"
else:
    gebco_var = list(gebco_dataset.data_vars)[0]

gebco = gebco_dataset[gebco_var]

rename_map = {}
if lat_name != "lat":
    rename_map[lat_name] = "lat"
if lon_name != "lon":
    rename_map[lon_name] = "lon"

if rename_map:
    gebco = gebco.rename(rename_map)

gebco = gebco.assign_coords(lon=((gebco["lon"].astype(float) + 180.0) % 360.0) - 180.0)
gebco = gebco.sortby("lon").sortby("lat")
gebco = gebco.sel(lat=slice(LAT_MIN, LAT_MAX))

lat_step = max(1, int(np.ceil(gebco.sizes["lat"] / 360)))
lon_step = max(1, int(np.ceil(gebco.sizes["lon"] / 720)))

gebco = gebco.isel(
    lat=slice(None, None, lat_step),
    lon=slice(None, None, lon_step)
).load()

gebco_dataset.close()


# 10. TABLE → MATRIX
def ensure_significance_column(table):
    out = table.copy()
    if "sig" not in out.columns:
        out["sig"] = ""
    out["sig"] = out["sig"].fillna("").astype(str)
    return out

panel_a = ensure_significance_column(panel_a)
panel_b = ensure_significance_column(panel_b)
panel_c = ensure_significance_column(panel_c)
panel_d = ensure_significance_column(panel_d)
panel_e = ensure_significance_column(panel_e)
panel_g = ensure_significance_column(panel_g)


def table_to_matrix(table, categories, value_column, category_column):
    values = np.full((len(SEA_ORDER), len(categories)), np.nan, dtype=float)
    symbols = np.full((len(SEA_ORDER), len(categories)), "", dtype=object)

    sea_lookup = {sea: i for i, sea in enumerate(SEA_ORDER)}
    category_lookup = {category: i for i, category in enumerate(categories)}

    for _, row in table.iterrows():
        sea = row["sea"]
        category = row[category_column]

        if sea not in sea_lookup or category not in category_lookup:
            continue

        i = sea_lookup[sea]
        j = category_lookup[category]
        values[i, j] = row[value_column]
        symbols[i, j] = row["sig"]

    return values, symbols


matrix_a, symbols_a = table_to_matrix(panel_a, PANEL_A_COLUMNS, "r", "driver")
matrix_b, symbols_b = table_to_matrix(panel_b, PANEL_B_COLUMNS, "r", "driver")
matrix_c, symbols_c = table_to_matrix(panel_c, PANEL_C_COLUMNS, "r", "driver")
matrix_d, symbols_d = table_to_matrix(panel_d, PANEL_D_COLUMNS, "beta", "predictor")
matrix_e, symbols_e = table_to_matrix(panel_e, PANEL_E_COLUMNS, "beta", "predictor")

matrix_g = np.full((len(SEA_ORDER), len(LAGS)), np.nan, dtype=float)
symbols_g = np.full((len(SEA_ORDER), len(LAGS)), "", dtype=object)

for i, sea in enumerate(SEA_ORDER):
    sea_table = panel_g[panel_g["sea"] == sea]
    for j, lag in enumerate(LAGS):
        row = sea_table[sea_table["lag"] == lag]
        if len(row) == 1:
            matrix_g[i, j] = row["r"].iloc[0]
            symbols_g[i, j] = row["sig"].iloc[0]


# 11. HEATMAP DRAWING
def draw_heatmap_panel(
    figure,
    cell,
    matrix,
    symbols,
    column_labels,
    panel_title,
    colorbar_label,
    cmap,
    norm,
    cell_font_size=FONT_CELL,
    title_height=5.1,
    title_y=0.58,
):
    """
    Draw one heatmap using three completely separate vertical bands:

    1. panel title;
    2. variable labels + heatmap;
    3. horizontal colorbar.

    The enlarged title band prevents the panel title from touching the
    variable labels at the top of the heatmap.
    """
    sub = cell.subgridspec(
        3,
        1,
        height_ratios=[title_height, 18.7, 1.35],
        hspace=0.15,
    )

    ax_title = figure.add_subplot(sub[0, 0])
    ax_main = figure.add_subplot(sub[1, 0])
    ax_cbar = figure.add_subplot(sub[2, 0])

    ax_title.set_axis_off()
    ax_title.text(
        0.5,
        title_y,
        panel_title,
        ha="center",
        va="center",
        fontsize=FONT_PANEL_TITLE,
        fontweight="bold",
        linespacing=1.08,
        clip_on=False,
    )

    img = ax_main.imshow(
        matrix,
        cmap=cmap,
        norm=norm,
        aspect="auto",
        interpolation="nearest",
    )

    ax_main.set_xticks(np.arange(len(column_labels)))
    ax_main.set_xticklabels(
        column_labels,
        fontsize=FONT_COLUMN,
        fontweight="bold",
        linespacing=0.98,
    )
    ax_main.xaxis.tick_top()
    ax_main.tick_params(
        axis="x",
        top=True,
        labeltop=True,
        bottom=False,
        labelbottom=False,
        length=0,
        pad=1.5,
    )

    ax_main.set_yticks(np.arange(len(SEA_ORDER)))
    ax_main.set_yticklabels(
        SEA_ORDER,
        fontsize=FONT_TICK,
        fontweight="bold",
    )
    ax_main.tick_params(axis="y", length=0, pad=2.0)

    ax_main.set_xticks(np.arange(-0.5, len(column_labels), 1), minor=True)
    ax_main.set_yticks(np.arange(-0.5, len(SEA_ORDER), 1), minor=True)
    ax_main.grid(which="minor", color="white", linewidth=0.95)
    ax_main.tick_params(which="minor", bottom=False, left=False)

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            value = matrix[i, j]
            if not np.isfinite(value):
                continue

            ax_main.text(
                j,
                i,
                f"{value:.2f}{symbols[i, j]}",
                ha="center",
                va="center",
                fontsize=cell_font_size,
                fontweight="bold",
                color="black",
                clip_on=True,
            )

    cbar = figure.colorbar(
        img,
        cax=ax_cbar,
        orientation="horizontal",
    )
    cbar.set_ticks([-1.0, -0.5, 0.0, 0.5, 1.0])
    cbar.ax.tick_params(labelsize=FONT_TICK, length=2.5, pad=1.2)

    for tick_label in cbar.ax.get_xticklabels():
        tick_label.set_fontweight("bold")

    cbar.set_label(
        colorbar_label,
        fontsize=FONT_AXIS,
        fontweight="bold",
        labelpad=2.0,
    )

    return ax_main


# 12. POLAR MAP HELPERS
def circular_boundary():
    theta = np.linspace(0.0, 2.0 * np.pi, 361)
    vertices = (
        np.vstack([np.sin(theta), np.cos(theta)]).T
        * 0.5
        + np.array([0.5, 0.5])
    )
    return MplPath(vertices)


def add_sector_boundaries(ax):
    for info in SEA_SECTORS.values():
        ax.plot(
            [info["lon_min"], info["lon_min"]],
            [LAT_MAX, -88.0],
            transform=ccrs.PlateCarree(),
            color="0.35",
            linewidth=0.55,
            zorder=9,
        )


def add_map_labels(ax):
    lon_labels = [
        (-180.0, "180°"),
        (-120.0, "120°W"),
        (-60.0, "60°W"),
        (60.0, "60°E"),
        (120.0, "120°E"),
        (180.0, "180°"),
    ]

    for lon, txt in lon_labels:
        ax.text(
            lon,
            -58.7,
            txt,
            transform=ccrs.PlateCarree(),
            fontsize=FONT_MAP,
            fontweight="bold",
            ha="center",
            va="center",
            clip_on=False,
            zorder=30,
        )

    ax.text(
        0.0,
        -61.0,
        "60°S",
        transform=ccrs.PlateCarree(),
        fontsize=FONT_MAP,
        fontweight="bold",
        ha="center",
        va="center",
        zorder=30,
        bbox=dict(
            boxstyle="round,pad=0.05",
            facecolor="white",
            edgecolor="none",
            alpha=0.45,
        ),
    )

    ax.text(
        0.5,
        0.5,
        "90°S",
        transform=ax.transAxes,
        fontsize=FONT_MAP,
        fontweight="bold",
        ha="center",
        va="center",
        zorder=30,
    )


def draw_composite_panel(
    figure,
    cell,
    composite_field,
    significance_field,
    gebco_field,
    positive_count,
    negative_count,
):
    outer = cell.subgridspec(
        2,
        1,
        height_ratios=[4.8, 18.4],
        hspace=0.04,
    )

    ax_title = figure.add_subplot(outer[0, 0])
    ax_title.axis("off")
    ax_title.text(
        0.5,
        0.66,
        "(h) Positive-minus-negative AAO\nSLA composite",
        ha="center",
        va="center",
        fontsize=FONT_PANEL_TITLE,
        fontweight="bold",
        linespacing=1.02,
        clip_on=False,
    )

    lower = outer[1, 0].subgridspec(
        1,
        4,
        width_ratios=[2.6, 20.8, 1.55, 2.6],
        wspace=0.22,
    )

    proj = ccrs.SouthPolarStereo()
    ax_map = figure.add_subplot(lower[0, 1], projection=proj)
    ax_cbar = figure.add_subplot(lower[0, 2])

    # Center the map–colorbar bundle within the whole panel.
    ax_map.set_anchor("C")
    ax_cbar.set_anchor("W")

    ax_map.set_extent([LON_MIN, LON_MAX, LAT_MIN, LAT_MAX], crs=ccrs.PlateCarree())
    ax_map.set_boundary(circular_boundary(), transform=ax_map.transAxes)

    ax_map.gridlines(
        crs=ccrs.PlateCarree(),
        draw_labels=False,
        xlocs=np.arange(-180, 181, 30),
        ylocs=[-60, -75],
        linewidth=0.45,
        linestyle=":",
        color="0.58",
        alpha=0.75,
        zorder=2,
    )

    finite = np.abs(composite_field.values[np.isfinite(composite_field.values)])
    if finite.size:
        vmax = float(np.nanpercentile(finite, 98.0))
    else:
        vmax = 1.0
    vmax = max(0.5, np.ceil(vmax * 2.0) / 2.0)

    norm = mcolors.TwoSlopeNorm(vmin=-vmax, vcenter=0.0, vmax=vmax)

    img = ax_map.pcolormesh(
        composite_field["lon"].values,
        composite_field["lat"].values,
        composite_field.values,
        transform=ccrs.PlateCarree(),
        cmap="RdBu_r",
        norm=norm,
        shading="auto",
        zorder=4,
    )

    gebco_lon_2d, gebco_lat_2d = np.meshgrid(
        gebco_field["lon"].values,
        gebco_field["lat"].values,
    )

    elev = gebco_field.values
    land = np.where(elev >= 0.0, 1.0, np.nan)

    ax_map.contourf(
        gebco_lon_2d,
        gebco_lat_2d,
        land,
        levels=[0.5, 1.5],
        colors=["0.84"],
        transform=ccrs.PlateCarree(),
        zorder=8,
    )

    ax_map.contour(
        gebco_lon_2d,
        gebco_lat_2d,
        elev,
        levels=[0.0],
        colors="0.30",
        linewidths=0.58,
        transform=ccrs.PlateCarree(),
        zorder=10,
    )

    add_sector_boundaries(ax_map)
    add_map_labels(ax_map)

    sigmask = significance_field.values.astype(bool)
    if sigmask.any():
        lon2d, lat2d = np.meshgrid(
            significance_field["lon"].values,
            significance_field["lat"].values,
        )

        sig_count = int(sigmask.sum())
        stride = max(1, int(np.ceil(np.sqrt(sig_count / 4200.0))))

        mask_sub = sigmask[::stride, ::stride]
        lon_sub = lon2d[::stride, ::stride]
        lat_sub = lat2d[::stride, ::stride]

        rr, cc = np.where(mask_sub)
        ax_map.scatter(
            lon_sub[rr, cc],
            lat_sub[rr, cc],
            transform=ccrs.PlateCarree(),
            s=1.4,
            marker="o",
            facecolor="black",
            edgecolor="none",
            alpha=0.66,
            zorder=12,
        )

    ax_map.text(
        0.03,
        0.035,
        f"AAO+ n={positive_count}\nAAO− n={negative_count}",
        transform=ax_map.transAxes,
        ha="left",
        va="bottom",
        fontsize=FONT_STATS_BOX,
        fontweight="bold",
        bbox=dict(
            boxstyle="round,pad=0.22",
            facecolor="white",
            edgecolor="0.42",
            alpha=0.96,
        ),
        zorder=35,
    )

    cbar = figure.colorbar(
        img,
        cax=ax_cbar,
        orientation="vertical",
        extend="both",
    )
    cbar.set_ticks(np.linspace(-vmax, vmax, 5))
    cbar.ax.tick_params(labelsize=FONT_TICK, length=2.8, pad=2.0)

    for t in cbar.ax.get_yticklabels():
        t.set_fontweight("bold")

    cbar.set_label(
        "SLA composite (cm)",
        fontsize=FONT_AXIS,
        fontweight="bold",
        rotation=90,
        labelpad=8.0,
    )


# 13. BUILD FIGURE: 2 COLUMNS × 4 ROWS
fig = plt.figure(figsize=FIGSIZE)

outer = fig.add_gridspec(
    5,
    2,
    left=0.055,
    right=0.965,
    top=0.987,
    bottom=0.085,
    height_ratios=[1.0, 1.0, 1.0, 1.0, 0.34],
    hspace=0.28,
    wspace=0.12,
)

# row 1
draw_heatmap_panel(
    fig, outer[0, 0],
    matrix_a, symbols_a,
    ["Total\nsteric", "Thermo-\nsteric", "Halo-\nsteric"],
    "(a) SLA–steric\ncorrelations",
    "Correlation (r)",
    CORR_CMAP, CORR_NORM,
    cell_font_size=FONT_CELL,
    title_height=5.3,
)

draw_heatmap_panel(
    fig, outer[0, 1],
    matrix_b, symbols_b,
    ["OHC", "SST", "Qnet*", "WSC", "MLD", "SIC", "AAO"],
    "(b) Thermosteric-driver correlations",
    "Correlation (r)",
    CORR_CMAP, CORR_NORM,
    cell_font_size=FONT_CELL,
    title_height=4.7,
)

# row 2
draw_heatmap_panel(
    fig, outer[1, 0],
    matrix_c, symbols_c,
    ["FWC", "SSS\nanomaly", "SIC", "Snowfall", "MLD", "Strati-\nfication", "AAO"],
    "(c) Halosteric-driver\ncorrelations",
    "Correlation (r)",
    CORR_CMAP, CORR_NORM,
    cell_font_size=FONT_CELL,
    title_height=5.5,
)

draw_heatmap_panel(
    fig, outer[1, 1],
    matrix_d, symbols_d,
    ["Qnet*", "WSC", "MLD", "SIC", "AAO"],
    "(d) Thermosteric regression\nstandardized coefficients (β)",
    "Standardized β",
    COEF_CMAP, COEF_NORM,
    cell_font_size=FONT_CELL,
    title_height=5.8,
)

# row 3
draw_heatmap_panel(
    fig, outer[2, 0],
    matrix_e, symbols_e,
    ["FWC", "SIC", "Snowfall", "MLD", "AAO"],
    "(e) Halosteric regression\nstandardized coefficients (β)",
    "Standardized β",
    COEF_CMAP, COEF_NORM,
    cell_font_size=FONT_CELL,
    title_height=5.8,
)

sub_f = outer[2, 1].subgridspec(2, 1, height_ratios=[3.0, 19.0], hspace=0.04)
axf_title = fig.add_subplot(sub_f[0, 0])
axf_title.axis("off")
axf_title.text(
    0.5, 0.56,
    "(f) AAO monthly time series",
    ha="center", va="center",
    fontsize=FONT_PANEL_TITLE,
    fontweight="bold",
)

axf = fig.add_subplot(sub_f[1, 0])
axf.axhspan(1.0, 3.0, color="#9ad79a", alpha=0.30, zorder=0)
axf.axhspan(-3.0, -1.0, color="#9bbde8", alpha=0.30, zorder=0)
monthly_line = axf.plot(aao_standardized.index, aao_standardized.values, color="0.68", linewidth=0.95, label="Monthly AAO", zorder=2)[0]
running_line = axf.plot(aao_running_mean.index, aao_running_mean.values, color="red", linewidth=1.45, label="3-month mean", zorder=3)[0]
axf.axhline(0.0, color="0.20", linewidth=0.85)
axf.axhline(1.0, color="0.30", linewidth=0.75, linestyle="--")
axf.axhline(-1.0, color="0.30", linewidth=0.75, linestyle="--")
axf.set_xlim(aao_standardized.index.min(), aao_standardized.index.max())
axf.set_ylim(-3.0, 3.0)
axf.set_ylabel("Standardized AAO", fontsize=FONT_AXIS, fontweight="bold")
axf.set_xlabel("Year", fontsize=FONT_AXIS, fontweight="bold", labelpad=2.0)
axf.xaxis.set_major_locator(mdates.YearLocator(4))
axf.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
axf.tick_params(axis="both", labelsize=FONT_TICK, pad=2.0)
for t in axf.get_xticklabels():
    t.set_rotation(45)
    t.set_ha("right")
    t.set_fontweight("bold")
for t in axf.get_yticklabels():
    t.set_fontweight("bold")
line_legend = axf.legend(handles=[monthly_line, running_line], loc="upper right", fontsize=FONT_LEGEND, frameon=True, framealpha=0.96, borderpad=0.36, labelspacing=0.30, handlelength=1.8)
axf.add_artist(line_legend)
phase_handles = [
    Patch(facecolor="#9ad79a", edgecolor="0.40", alpha=0.45, label="AAO ≥ +1: positive phase"),
    Patch(facecolor="#9bbde8", edgecolor="0.40", alpha=0.45, label="AAO ≤ −1: negative phase"),
]
axf.legend(handles=phase_handles, loc="lower left", fontsize=FONT_LEGEND, frameon=True, framealpha=0.96, borderpad=0.34, labelspacing=0.28, handlelength=1.4)

# row 4
draw_heatmap_panel(
    fig, outer[3, 0],
    matrix_g, symbols_g,
    [f"+{lag}" if lag > 0 else str(lag) for lag in LAGS],
    "(g) AAO–SLA lag correlation\nPositive lag: AAO leads SLA",
    "Correlation (r)",
    CORR_CMAP, CORR_NORM,
    cell_font_size=FONT_CELL_LAG,
    title_height=6.0,
)

draw_composite_panel(fig, outer[3, 1], composite, composite_significant, gebco, n_positive, n_negative)


# ======================================================================
# 14. FOOTNOTES
# ======================================================================
median_adj_r2_thermo = float(panel_d.groupby("sea")["adjusted_r2"].first().median())
median_adj_r2_halo = float(panel_e.groupby("sea")["adjusted_r2"].first().median())
combined_vif = np.concatenate([panel_d["vif"].to_numpy(dtype=float), panel_e["vif"].to_numpy(dtype=float)])
max_vif = float(np.nanmax(combined_vif))

note_ax = fig.add_subplot(outer[4, :])
note_ax.set_axis_off()

footnote_paragraph = (
    "Cell symbols: • q < 0.10; * q < 0.05; ** q < 0.01. "
    "Correlation significance: Benjamini–Hochberg FDR with AR(1)-adjusted effective sample size; "
    "panel (h) uses year-block bootstrap stippling. "
    f"Regression: HAC(1); median adjusted R² = {median_adj_r2_thermo:.2f} / {median_adj_r2_halo:.2f}; "
    f"maximum VIF = {max_vif:.1f}. "
    "Qnet* = SSRD + STRD + signed SLHF + signed SSHF (surface heat-flux proxy; true net heat flux requires ERA5 SSR and STR)."
)

note_ax.text(
    0.012,
    0.50,
    footnote_paragraph,
    ha="left",
    va="center",
    fontsize=FONT_NOTE,
    fontweight="bold",
    wrap=True,
    clip_on=False,
)

# 15. SAVE
print("Saving PDF...")
fig.savefig(OUT_PDF, facecolor="white", edgecolor="none", bbox_inches=None)
gc.collect()
print("Saving PNG at 1080 dpi...")
fig.savefig(OUT_PNG, dpi=SAVE_DPI, facecolor="white", edgecolor="none", bbox_inches=None, pil_kwargs={"compress_level": 6})
plt.close(fig)
gc.collect()


# 16. LOG
log_lines = [
    "=" * 92,
    "FIGURE 13 — FINAL V3 2-COLUMN × 4-ROW PLOT-ONLY VERSION",
    "=" * 92,
    "",
    "No scientific calculations were recomputed.",
    "",
    "Corrections applied:",
    "• Layout changed to 2 columns × 4 rows.",
    "• Larger panel titles, labels, legends, tick labels, and footnotes.",
    "• Larger numeric text inside every heatmap cell.",
    "• Panel (h) colorbar label restored: SLA (cm).",
    "• Taller dedicated title bands prevent title/variable-label overlap.",
    "• Full labels used for SSS anomaly, Snowfall and Stratification.",
    "• Panel (h) colorbar moved next to the map and labelled SLA composite (cm).",
    "• Bottom methodological note rendered as one wrapped paragraph with larger text.",
    "• Uses processed CSV/NetCDF outputs only.",
    "",
    f"PNG: {OUT_PNG}",
    f"PDF: {OUT_PDF}",
]

OUT_LOG.write_text("\n".join(log_lines), encoding="utf-8")
print("\n".join(log_lines))
print("\nFigure 13 final V3 corrected layout completed.")
